services:
  web_server:
    build: .
    ports:
      - ${WEB_SERVER_PORT}:3000
    depends_on:
      - database
      #- redis
    container_name: 2dam_inventory_movil-webserver
    working_dir: /web
    command: pm2-runtime start pm2.json
    volumes:
      - ./2dam_inventory:/web
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  database:
    image: yobasystems/alpine-mariadb:10.11.8
    container_name: 2dam-inventory_movil-db
    ports:
      - "2222:3306"
    #restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=UTC
    volumes:
     - ./data/db/mysql:/var/lib/mysql
  #    - ./mysql.cnf:/etc/mysql/my.cnf
  # redis: 
  #   image: 'redis'
  #   container_name: 2dam_inventory-redis
